trigger:
- master

jobs:
- job: Job1
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: KubernetesManifest@0
    displayName: Deploy manifests
    inputs:
      kubernetesServiceEndpoint: k8sSC
      manifests: 'manifests/curl.yml'
    timeoutInMinutes: 2
- job: Job2
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: KubernetesManifest@0
    displayName: Deploy manifests
    inputs:
      kubernetesServiceEndpoint: k8sSC
      manifests: 'manifests/imagepullsecretnotconfigured.yml'
    timeoutInMinutes: 2
- job: Job3
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: KubernetesManifest@0
    displayName: Deploy manifests
    inputs:
      kubernetesServiceEndpoint: k8sSC
      manifests: 'manifests/probe-exec-liveness.yml'
    timeoutInMinutes: 2
