apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgpullsecretnotconfigured
  labels:
    app: imgpullsecretnotconfigured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imgpullsecretnotconfigured
  template:
    metadata:
      labels:
        app: imgpullsecretnotconfigured
    spec:
      containers:
      - name: demo
        image: shasb.azurecr.io/playground-orders:test
        ports:
        - containerPort: 80

